name: Code Quality and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff build
          pip install -e ".[test]"
          
      - name: Check code formatting with Black
        run: black --check .
        
      - name: Lint with Ruff
        run: ruff check .
        
      - name: Run tests
        run: |
          pytest -v --cov=ticked --cov-report=xml --cov-report=term
        
      - name: Check if package builds correctly
        run: python -m build
